version: '2.1'
orbs:
  aws-ecs: circleci/aws-ecs@2.0
  aws-cli: circleci/aws-cli@1.3
  orb-tools: circleci/orb-tools@10.0
  shellcheck: circleci/shellcheck@2.2
  jq: circleci/jq@2.2.0

  
jobs:
    test-apache:
      docker:
        - image: cimg/base:stable
      steps:
       - aws-cli/setup
       - jq/install
       - run:
            name: Get Cluster Info
            command: |
              ECS_CLUSTER_NAME=${ECS_CLUSTER_NAME}
              ECS_SERVICE_NAME=${ECS_SERVICE_NAME}
              SERVICE_OBJ=$(aws ecs describe-services --cluster $ECS_CLUSTER_NAME --services $ECS_SERVICE_NAME)
              VPC_OBJ=$(echo $SERVICES_OBJ | jq  '.services[].networkConfiguration.awsvpcConfiguration')
              SUBNET_ONE= $(echo $VPC_OBJ | jq '.subnet[0]')
              SUBNET_TWO= $(echo $VPC_OBJ | jq '.subnet[1]')
              SECURITY_GROUP_IDS= $(echo $VPC_OBJ | jq '.securityGroups[0]')
              CLUSTER_NAME=echo $(echo $SERVICE_OBJ | jq '.services[].clusterArn')
              echo "export SUBENT_ONE = $SUBENT_ONE" >> $BASH_ENV
              echo "export SUBENT_TWO = $SUBENT_TWO" >>BASH_ENV
              echo "export  SECURITY_GROPS_ID = $SECURITY_GROUP_ID" >> $BASH_ENV=$SECURITY_GROUP_IDS=$SECURITY_GROUP_IDS" >> $BASH_ENV" >> $BASH_ENV
              echo "export CLUSTER_NAME= $CLUSTER_NAME" >> BASH_ENV
workflows:
  run-task:
    jobs:
      - test-apache:
          context: ecs-deployment
